# Stage 1: Build
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS builder
WORKDIR /src
ENV DOTNET_NOLOGO=true \
    DOTNET_CLI_TELEMETRY_OPTOUT=true \
    NUGET_XMLDOC_MODE=skip

COPY NuGet.config ./
COPY *.sln ./
COPY FMDC/FMDC.csproj FMDC/
COPY Domain/Domain.csproj Domain/

RUN dotnet restore FMDC.sln

COPY . .
WORKDIR "/src/FMDC"

RUN dotnet build "FMDC.csproj" -c Debug

RUN dotnet publish "FMDC.csproj" -c Debug -o /app/publish --no-build

# Stage 2: Development Runtime
FROM mcr.microsoft.com/dotnet/sdk:10.0
WORKDIR /app
ENV ASPNETCORE_URLS="http://+:4000" \
    ASPNETCORE_ENVIRONMENT="Development" \
    DOTNET_NOLOGO=true \
    DOTNET_CLI_TELEMETRY_OPTOUT=true 

# Install debugger
RUN apt-get update && \
    apt-get install -y --no-install-recommends curl unzip && \
    rm -rf /var/lib/apt/lists/* && \
    curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /vsdbg

COPY --from=builder /app/publish .

EXPOSE 4000

ENTRYPOINT ["dotnet", "FMDC.dll"]
